trigger: none

jobs:
- job:
  pool:
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04
  
  # refer to https://github.com/MicrosoftDocs/pipelines-go/blob/main/azure-pipelines.yml
  variables:
    GOBIN:  '$(GOPATH)/bin' # Go binaries path
    GOROOT: '/usr/local/go1.22.2' # Go installation path
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

  steps:
  - task: GoTool@0
    inputs:
      version: '1.22.2'
  
  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      shopt -s dotglob
      mv !(gopath) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: 'Set up the Go workspace'

  - script: |
      go version
      go install github.com/azure/armstrong@109e9a46faa57c2c5af762019342dff3030f7d79
    displayName: 'Install go dependencies'

  - pwsh: |
      Get-ChildItem -Path $(Build.SourcesDirectory)/eng/scripts
      $(Build.SourcesDirectory)/eng/scripts/Armstrong-Validation.ps1 -Verbose
    displayName: Armstrong Validation
    ignoreLASTEXITCODE: true
